### ISSUE TITLE
The SearchCatalogItems202204 interface of the CatalogItemService cannot be called

### ISSUE THREAD

**Issue by Kofslime** [abuzuhri/Amazon-SP-API-CSharp#308]
The SearchCatalogItems202204 interface of the CatalogItemService cannot be called after the websiteDisplayGroupName attribute is added. The exception message is "Amazon Api didn't respond with Okay, see exception for more details"

**Comment by gambit823** [comment]
I am having the same issue with Orders.GetOrderItems. I've tracked it down to the fix for issue https://github.com/abuzuhri/Amazon-SP-API-CSharp/issues/287. That fix added the following line to Source/FikaAmazonAPI/Services/RequestService.cs:
RequestClient.ThrowOnAnyError = true;

If you remove that line everything works again.

**Comment by abuzuhri** [comment]
Please check v1.4.26
