### ISSUE TITLE
FulfillmentInbound.ProNumber

### ISSUE THREAD

**Issue by MasterTyrr** [abuzuhri/Amazon-SP-API-CSharp#327]
There is a problem with the FulfillmentInbound.puttransportdetails.nonpartneredltlinput. It requires a ProNumber, which can't seem to be set. According to the documentation, it is a string that is being sent. The class can probably be removed and require any input that requires a Pro number just accept a pronumber as a string. 

My Code:
putTransportDetailsRequest.ShipmentType = ShipmentType.LTL;
var ltlInputData = new NonPartneredLtlDataInput();
ProNumber proNum = new ProNumber();
proNum.Equals(coTrackNum);

ltlInputData.CarrierName = coMethod;
ltlInputData.ProNumber = proNum;
transportDetails.NonPartneredLtlData = ltlInputData;

What the documentation says about ProNumbers
> ProNumber
> The PRO number ("progressive number" or "progressive ID") assigned to the shipment by the carrier.
> Type : string

**Comment by RenzoF** [comment]
Hi, @MasterTyrr  I think you are right and this could be changed to a string though the issue here is with the original model that points to a class rather than a string.

https://github.com/amzn/selling-partner-api-models/blob/c2383c7e6526f4e133cb12dc8397ff586e536440/models/fulfillment-inbound-api-model/fulfillmentInboundV0.json#L5426

Might be worth opening an issue there as well

**Comment by abuzuhri** [comment]
@RenzoF i feel you active here i will add you as contribution and you can start fix small bug like this in future

**Comment by abuzuhri** [comment]
@MasterTyrr problem solved in v1.4.29
