### ISSUE TITLE
Turn off Role ARN

### ISSUE THREAD

**Issue by jmawebtech** [abuzuhri/Amazon-SP-API-CSharp#533]
Hi,

When I registered my Amazon app, I used a user ARN:

arn:aws:iam::XXX:user/XXX

When I call code to get finances, I get this error:

Amazon.SecurityToken.AmazonSecurityTokenServiceException: 'User: arn:aws:iam::XXX:user/XXXis not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::XXX:user/XXX

Do I have to use a role ARN?

Here is the code that I called:

.Financial.ListFinancialEvents(new FikaAmazonAPI.Parameter.Finance.ParameterListFinancialEvents()
            {
                PostedAfter = DateTime.Now.AddDays(-14),
                PostedBefore = DateTime.Now
            });

When I use an role ARN, I get this error:

FikaAmazonAPI.AmazonSpApiSDK.Models.Exceptions.AmazonUnauthorizedException: 'Access to requested resource is denied.'

Is there a way to turn off the role ARN code and just use an access token? Do I need to update my app listing to use the role ARN instead of the user?

In my user, I added this policy:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "sts:GetSessionToken",
                "sts:DecodeAuthorizationMessage",
                "sts:GetAccessKeyInfo",
                "sts:GetCallerIdentity",
                "sts:GetServiceBearerToken"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "sts:*",
            "Resource": "arn:aws:iam::XX:user/XX"
        }
    ]
}

**Comment by sat-it** [comment]
Hi,

i read that you should use role arn (not user arn).

Instructions:
https://developer-docs.amazon.com/sp-api/docs/creating-and-configuring-iam-policies-and-entities

in AWS account.
Identity and Access Management (IAM)
Role
arn:aws:iam::12345789:role/"Name"
copy this value

and use it in your sellercentral account
Developer Central
IAM ARN

For 'Access to requested resource is denied.':
Check roles permissions (Product Listing, Pricing etc) in Developer Profile (sellercentral account).

Maybe try another call for testing, which has a role permission.
Example for order
var data = amazonConnection.Orders.GetOrder(new FikaAmazonAPI.Parameter.Order.ParameterGetOrder()
                {
                    IsNeedRestrictedDataToken = false,
                    OrderId = "XXX"
                });

Example for CatalogItem 
ParameterGetCatalogItem parameterListCatalogItem = new ParameterGetCatalogItem();
parameterListCatalogItem.ASIN = "XXX";
var item = amazonConnection.CatalogItem.GetCatalogItem202204(parameterListCatalogItem);

To "In my user, I added this policy:..." -  i'm not sure, i can't find it in the instructions.

conclusion: with instructions, role-arn and (existing) roles-permissions it works.

Best regards

**Comment by jmawebtech** [comment]
Yes, you must use the role ARN in your Amazon app.

**Comment by guruksk** [comment]
https://github.com/abuzuhri/Amazon-SP-API-CSharp/issues/565

Amazon support team asking us to use the UserARN only for our 'App Client' in Developer Central page. So we are asked to skip Security Token Service (STS) api call during postman execution.
We generate LWA token and then directly call SP-Api, and everything working fine, able to call the reports api and get response.

Since Amazon support team itself mentioning to use UserARN in some case and also Amazon C# SDK also provide option to call the SP api's without using RoleARN
https://developer-docs.amazon.com/sp-api-blog/docs/automate-your-sp-api-calls-using-the-c-sdk

As per few discussion in issues/29 & issues/533, I can understand CSharpAmazonSpAPI will not work without RoleArn

1. Why CSharpAmazonSpAPI made mandatory to pass RoleArn?
2. Do we have any plans to support UserARN or allow to call SP-api without RoleArn?

Please provide your valuable answer. Advance thanks.
