### ISSUE TITLE
Issue In POST_PAYMENT_ADJUSTMENT_DATA Feed

### ISSUE THREAD

**Issue by kapildel** [abuzuhri/Amazon-SP-API-CSharp#582]
My XML is like that when i construct OrderAdjustmentMessage and Executed amzcon.Feed.SubmitFeed with below XML..
  
NOTE: -- In adjustmentprice elelment   xsd:element name="Component" maxOccurs="unbounded"> is missing why??

[xmlFeed.txt](https://github.com/abuzuhri/Amazon-SP-API-CSharp/files/11614187/xmlFeed.txt)

Feed is Getting submitted but the result i am getting in feed result is 
MessagesProcessed=1
MessagesSuccessful= 0
MessagesWithError=1
MessagesWithWarning=0
  > This is a malformed or invalid XML document. For more details, please see http://sellercentral.amazon.com/gp/help/22971

can you please explain whats the issue in XML, i am using Lastest Fikaamazonapi dll?

**Comment by abuzuhri** [comment]
Personally I have no time to keep updating this package but I'm open any developer need to fix or add feature on it its take many times from me to get it live , and I need other developer help to add the fix for new features by submit new Pull requests , I will try to review and accept within 2 days  .


Please try fork our rep and then submit your change to review and merge with our code
