### ISSUE TITLE
Belgium domain changed from be to com.be

### ISSUE THREAD

**Issue by Xriuk** [abuzuhri/Amazon-SP-API-CSharp#603]
The new domain is: www.amazon.com.be
So it should be updated: https://github.com/abuzuhri/Amazon-SP-API-CSharp/blob/main/Source/FikaAmazonAPI/Utils/Country.cs

**Comment by abuzuhri** [comment]
Personally I have no time to keep updating this package but I'm open any person need to fix or add feature on it its take many times from me to get it live , and I need other developer help to add the fix for new features by submit new Pull requests , I will try to review and accept within 2 days  .


Please try fork our branch and then submit your change to review and merge with our code
